### ISSUE TITLE
Finalize tools which are required to build chat module

### ISSUE THREAD

**Issue by azfar10p** [10pearls/ng-papyrus#3]
Finalize tools which are required to build chat module such as JQuery, AngularJS any other front end framework etc..

**Comment by mohuk** [comment]
Since we are integrating it first with Angular so .. I am thinking Angular 1.5.x with the new component syntax on ES6/TS. The newer syntax is closer to the new era of component based frontend web apps i.e. Angular 2 and React.

This syntax will make it easier to port the component on Angular 2 and React later on.

**Comment by mohuk** [comment]
Here are some reference articles which I went through:
- [Component based style guide](https://github.com/toddmotto/angular-styleguide)
- [Component based style guide blog](https://toddmotto.com/rewriting-angular-styleguide-angular-2)
- [Component life cycle hooks](https://toddmotto.com/angular-1-5-lifecycle-hooks)

**Comment by mohuk** [comment]
Angular JS on webpack with TS. Going for Angular material for the UI framework.
